#!/usr/local/bin/python3
import os
import sys

arg = sys.argv
version = '1.0.0'

def install():
    os.system('pip install ' + arg[2])
def uninstall():
    os.system("pip uninstall " + arg[2])

if os.path.isfile(arg[1]) == True and '.py' in arg[1]:
    os.system('python3 ' + arg[1])
if arg[1] == 'run' and os.path.isfile(arg[2]) == True and '.py' in arg[2]:
    os.system('python3 ' + arg[2])

if arg[1] == 'create' and os.path.exists(arg[2]):
    print('this file all ready exists')
if arg[1] == 'create' and os.path.isfile(arg[2]) == False:
    print('working')
    f = open(arg[2], 'x')
if arg[1] == 'install':
    install()
if arg[1] == 'uninstall':
    uninstall()
if arg[1] == 'print':
    print('\n' + str(sys.argv[2]))
if arg[1] == '--help':
    print('<create> <file name with extsion>')
    print('<delete> <file name with extsion>')
    print('<print> <and what you want to print on the ternmial>')
    print('<install> <to install a pip packages>')
    print('<uninstall> <to uninstall pip packages>')
    print('<run> or <no run command if you choose> <to run a python script>')
    print('<--version> <get the version of pyhelper')
    print('<--help> <to show a list of commands>')
if arg[1] == '--version':
    print('\n' + version)

if arg[1] == 'delete':
    os.remove(arg[2])
    print('removed')

if arg[1] == 'print' or arg[1] == 'create' or arg[1] == 'install' or arg[1] == 'uninstall' or arg[1] == 'delete' or arg[1] == '--version' or arg[1] == '--help' or arg[1] == 'run':
    print('')
else:
    print('sorry this command does not exists')
    print('to see all commands type pyhelper --help or to get the version type pyhelper --version')